# Generated by Django 4.2.2 on 2023-07-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toHome', '0002_remove_detalle_pedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen1',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
