# Generated by Django 4.2.2 on 2023-07-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toHome', '0003_alter_producto_imagen1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
