# Generated by Django 4.2.2 on 2023-07-08 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toShopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_pedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='toShopping.pedido'),
        ),
    ]
