# Generated by Django 4.2.3 on 2023-07-07 00:00

from django.db import migrations

PRODUCTS = [
    {
        'name': 'Desarrollo Front-End',
        'price': 10,
        'slug': 'item-2',
        'description': 'item 1 description'
    },
    {
        'name': 'Desarrollo back-end',
        'price': 20,
        'slug': 'item-2',
        'description': 'item 2 description'
    },
    {
        'name': 'Desarrollo de aplicativos moviles',
        'price': 40,
        'slug': 'item-3',
        'description': 'item 3 description'
    }
]


def add_products(apps, schema_editor):
    Product = apps.get_model('ecommerce_app', 'Product')

    for p in PRODUCTS:
        l = Product.objects.get_or_create(
            name=p['name'],
            price=p['price'],
            slug=p['slug'],
            description=p['description'],
        )

        print(p)


def remove_products(apps, schema_editor):
    Product = apps.get_model('ecommerce_app', 'Product')

    for p in PRODUCTS:
        l = Product.objects.get(
            slug=p['slug'],
        )

        l.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_products, remove_products)
    ]
