# Generated by Django 4.2.3 on 2023-07-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ecommerce_app",
            "0003_alter_cartitem_id_alter_lineitem_id_alter_order_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producto", models.CharField(max_length=100)),
                ("cantidad", models.IntegerField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=8)),
                ("fecha", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
